<script>
	/**
	 * /r/[id] — someone opened a link to one render.
	 *
	 * The render is the picture: a proof-sheet frame on the canvas ground at the
	 * render's own aspect (max 1200 wide), a mono ledger under it, the actions,
	 * then the embed codes beside the context card (or the creator's analytics).
	 * No decoration clusters.
	 *
	 * Behaviour is the live page's, untouched: getShareResult, the embed
	 * snippets, copy link, downloadAsset() and its
	 * /public/results/:uid/download conversion call, the creator analytics
	 * fetch, the source-aware CTA copy, and the headings (H1 title, H2 "Result
	 * not found" / the banner headline).
	 */
	import Nav from '$lib/components/landing/Nav.svelte';
	import Footer from '$lib/components/landing/Footer.svelte';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { PUBLIC_BACKEND_URL } from '$env/static/public';
	import { getShareResult } from '../../../api/public-templates.js';
	import { toast } from '../../../store/toast.store.js';
	import { user } from '../../../store/user.store.js';
	import backend from '../../../service/backend.js';

	// State
	let result = null;
	let template = null;
	let loading = true;
	let error = null;

	// Embed codes state
	let activeEmbedTab = 'img';

	// Download dropdown state
	let downloadOpen = false;
	let downloading = null;

	// Analytics state
	let analytics = null;
	let analyticsLoading = false;
	let analyticsFetched = false;

	$: id = $page.params.id;
	$: isLoggedIn = !!$user?.email;
	$: isCreator = isLoggedIn && result?.createdBy && $user?.email === result.createdBy;

	// Reactively fetch analytics when logged-in user is available and result is loaded.
	// Any team member (not just creator) can view analytics — the backend authorizes.
	$: if (isLoggedIn && result?.uid && !analyticsFetched) {
		analyticsFetched = true;
		fetchAnalytics();
	}

	// Tool slug map for context-aware CTA
	const toolSlugMap = {
		Screenshot: 'screenshot',
		'OG Image': 'og-image-generator',
		Banner: 'banner-generator',
		'Social Media': 'social-media-generator',
		Certificate: 'certificate-generator',
		Invoice: 'invoice-generator',
		Meme: 'meme-generator',
		Quote: 'quote-image-generator',
		Thumbnail: 'thumbnail-generator',
		Mockup: 'mockup-generator',
		Chart: 'chart-image-generator',
		'QR Code': 'qr-code-generator'
	};

	// Embed code snippets
	$: embedSnippets = result
		? {
				img: `<img loading="lazy" src="${result.assetUrl}" alt="${result.title || 'Pictify image'}" width="${
					result.width
				}" height="${result.height}" />`,
				markdown: `![${result.title || 'Pictify image'}](${result.assetUrl})`,
				html: `<picture><img src="${result.assetUrl}" alt="${
					result.title || 'Pictify image'
				}" width="${result.width}" height="${
					result.height
				}" style="max-width:100%;height:auto;" loading="lazy" /></picture>`,
				bbcode: `[img]${result.assetUrl}[/img]`
		  }
		: {};

	const embedTabs = [
		{ key: 'img', label: 'IMG TAG' },
		{ key: 'markdown', label: 'MARKDOWN' },
		{ key: 'html', label: 'HTML' },
		{ key: 'bbcode', label: 'BBCODE' }
	];

	// Source-aware CTA config
	$: ctaConfig = getCtaConfig(result);

	function getCtaConfig(r) {
		if (!r) return null;
		const toolSlug = r.toolName
			? toolSlugMap[r.toolName] || r.toolName.toLowerCase().replace(/\s+/g, '-')
			: 'tools';
		switch (r.source) {
			case 'tool':
				return {
					sidebar: {
						heading: `Made with ${r.toolName || 'Pictify Tools'}`,
						button: 'Try This Tool Free',
						link: `/tools/${toolSlug}`
					},
					banner: {
						headline: 'LIKE THIS? MAKE HUNDREDS.',
						body: 'Turn this design into a template. Render variants via API.'
					}
				};
			case 'template':
				return {
					sidebar: { heading: 'Built from Template', button: 'Build Your Own', link: '/signup' },
					banner: {
						headline: 'ONE TEMPLATE. INFINITE VARIANTS.',
						body: 'Build an HTML template, change the variables, batch render at scale.'
					}
				};
			case 'api':
				return {
					sidebar: { heading: 'Generated via API', button: 'Get Your API Key', link: '/signup' },
					banner: {
						headline: 'YOUR APP. AUTOMATED IMAGES.',
						body: 'Generated by a single API call. Ship it in your product.'
					}
				};
			default:
				return {
					sidebar: { heading: 'Created with Pictify', button: 'Try Pictify Free', link: '/signup' },
					banner: {
						headline: 'DESIGN. AUTOMATE. SCALE.',
						body: 'Create images, GIFs, and PDFs. Automate with the API.'
					}
				};
		}
	}

	// Fetch result details
	async function fetchResult() {
		loading = true;
		error = null;

		try {
			const response = await getShareResult(id);
			result = response.result;
			template = response.template;
		} catch (e) {
			error = e.message || 'Result not found';
		} finally {
			loading = false;
		}
	}

	// Copy URL to clipboard
	async function copyShareUrl() {
		try {
			await navigator.clipboard.writeText(window.location.href);
			toast.set({ message: 'Link copied!', type: 'success', duration: 1500 });
		} catch (e) {
			toast.set({ message: 'Failed to copy', type: 'error', duration: 2000 });
		}
	}

	// Copy embed code
	async function copyEmbedCode(tab) {
		const snippet = embedSnippets[tab];
		if (!snippet) return;
		try {
			await navigator.clipboard.writeText(snippet);
			toast.set({ message: 'Embed code copied!', type: 'success', duration: 1500 });
		} catch (e) {
			toast.set({ message: 'Failed to copy', type: 'error', duration: 2000 });
		}
	}

	// Download asset in given format
	function downloadAsset(format) {
		if (!result?.assetUrl) return;
		downloadOpen = false;

		const originalFormat = (result.format || 'png').toLowerCase();

		if (format === originalFormat || !format) {
			// Direct download of original
			const link = document.createElement('a');
			link.href = result.assetUrl;
			link.download = `pictify-${result.uid}.${originalFormat}`;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);
		} else {
			// Use conversion endpoint
			downloading = format;
			const downloadUrl = `${PUBLIC_BACKEND_URL}/public/results/${result.uid}/download?format=${format}&quality=90`;
			const link = document.createElement('a');
			link.href = downloadUrl;
			link.download = `pictify-${result.uid}.${format}`;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);
			setTimeout(() => {
				downloading = null;
			}, 2000);
		}
	}

	// Handle sidebar CTA click
	function handleSidebarCta() {
		if (ctaConfig?.sidebar?.link) {
			goto(ctaConfig.sidebar.link);
		}
	}

	// Fetch creator analytics
	async function fetchAnalytics() {
		if (!result?.uid) return;
		analyticsLoading = true;
		try {
			analytics = await backend.get(`/public/results/${result.uid}/analytics`);
		} catch (e) {
		} finally {
			analyticsLoading = false;
		}
	}

	// Format source name
	function formatSource(source) {
		const sources = {
			tool: 'Free Tool',
			template: 'Template',
			api: 'API',
			dashboard: 'Dashboard'
		};
		return sources[source] || source;
	}

	// Format date
	function formatDate(dateStr) {
		if (!dateStr) return '';
		const date = new Date(dateStr);
		return date.toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric'
		});
	}

	// Format bytes to human-readable
	function formatBytes(bytes) {
		if (!bytes || bytes === 0) return '0 B';
		const units = ['B', 'KB', 'MB', 'GB', 'TB'];
		const i = Math.floor(Math.log(bytes) / Math.log(1024));
		return (bytes / Math.pow(1024, i)).toFixed(i > 0 ? 1 : 0) + ' ' + units[i];
	}

	// Close download dropdown on outside click
	function handleClickOutside(event) {
		if (downloadOpen && !event.target.closest('.download-dropdown')) {
			downloadOpen = false;
		}
	}

	// Simple syntax highlighter for embed snippets (colours are v2 tokens on the press ground).
	// The inserted spans quote their class with ' not ": the attribute-value pass matches
	// "…", and double quotes here were being wrapped too, printing `text-brand-sky">` into
	// the code box.
	function highlightSnippet(code) {
		if (!code) return '';
		return code
			.replace(/&/g, '&amp;')
			.replace(/</g, '&lt;')
			.replace(/>/g, '&gt;')
			.replace(/(src|alt|width|height|style|loading)=/g, "<span class='text-brand-sky'>$1</span>=")
			.replace(/"([^"]*)"/g, "\"<span class='text-brand-field'>$1</span>\"")
			.replace(/(&lt;\/?)([\w-]+)/g, "$1<span class='text-brand-pink'>$2</span>")
			.replace(/(\[\/?\w+\])/g, "<span class='text-brand-pink'>$1</span>");
	}

	$: ledger = result
		? [
				['FORMAT', (result.format || 'png').toUpperCase()],
				['SIZE', result.width && result.height ? `${result.width} × ${result.height}` : null],
				['CREATED', formatDate(result.createdAt).toUpperCase()],
				['SOURCE', result.source ? formatSource(result.source).toUpperCase() : null],
				template?.name ? ['FROM TEMPLATE', `“${template.name}”`] : null,
				[
					'VIEWS',
					(analytics?.totalHits ? analytics.totalHits : result.viewCount || 0).toLocaleString('en-US')
				]
		  ].filter((row) => row && row[1])
		: [];

	onMount(() => {
		fetchResult();
		document.addEventListener('click', handleClickOutside);
		return () => document.removeEventListener('click', handleClickOutside);
	});
</script>

<svelte:head>
	{#if result}
		<title>{result.title || 'Shared Image'} | Pictify</title>
		<meta
			name="description"
			content="View this image created with Pictify. Generate unlimited variants with HTML templates and the API."
		/>
		<link rel="canonical" href={`https://pictify.io/r/${result.uid}`} />

		<!-- Open Graph -->
		<meta property="og:title" content={result.title || 'Created with Pictify'} />
		<meta
			property="og:description"
			content="View this image. Create your own with Pictify templates and the API."
		/>
		<meta property="og:type" content="website" />
		<meta property="og:site_name" content="Pictify" />
		<meta property="og:url" content={`https://pictify.io/r/${result.uid}`} />
		<meta property="og:image" content={result.assetUrl} />
		<meta property="og:image:width" content={result.width} />
		<meta property="og:image:height" content={result.height} />

		<!-- Twitter Card -->
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:title" content={result.title || 'Created with Pictify'} />
		<meta name="twitter:description" content="View this image, created with Pictify." />
		<meta name="twitter:image" content={result.assetUrl} />

		<!-- JSON-LD Structured Data -->
		{@html `<script type="application/ld+json">${JSON.stringify({
			'@context': 'https://schema.org',
			'@type': 'ImageObject',
			name: result.title || 'Created with Pictify',
			contentUrl: result.assetUrl,
			url: `https://pictify.io/r/${result.uid}`,
			width: result.width,
			height: result.height,
			encodingFormat:
				result.format === 'gif'
					? 'image/gif'
					: result.format === 'webp'
					? 'image/webp'
					: result.format === 'jpg'
					? 'image/jpeg'
					: 'image/png',
			dateCreated: result.createdAt,
			creator: {
				'@type': 'Organization',
				name: 'Pictify',
				url: 'https://pictify.io'
			}
		})}</script>`}
	{:else}
		<title>Shared Result | Pictify</title>
	{/if}
</svelte:head>

<div class="landing-v2 flex min-h-screen w-full flex-col bg-brand-canvas">
	<Nav />

	<main class="mx-auto flex w-full max-w-page flex-1 flex-col px-5 pb-20 pt-10 lg:px-10 lg:pt-14">
		{#if loading}
			<div class="flex min-h-[420px] flex-col items-center justify-center gap-4" aria-live="polite">
				<div class="flex gap-1.5" aria-hidden="true">
					<span class="h-3 w-3 animate-pulse bg-brand-blue" />
					<span class="h-3 w-3 animate-pulse bg-brand-ink [animation-delay:150ms]" />
					<span class="h-3 w-3 animate-pulse bg-brand-pink [animation-delay:300ms]" />
				</div>
				<p class="font-mono text-xs tracking-[0.06em] text-brand-mute">LOADING THE RENDER…</p>
			</div>
		{:else if error}
			<div
				class="mx-auto flex w-full max-w-[560px] flex-col items-start gap-4 rounded-tile border-[1.5px] border-brand-ink bg-brand-paper p-8"
			>
				<p class="font-mono text-xs tracking-[0.06em] text-brand-mute">SHARED LINK · 404</p>
				<h2
					class="font-display text-[32px] font-bold leading-[38px] tracking-[-0.02em] text-brand-ink"
				>
					Result not found
				</h2>
				<p class="font-sans text-[15px] leading-[23px] text-brand-slate">{error}</p>
				<a
					href="/tools"
					class="rounded-lg bg-brand-ink px-6 py-3.5 font-sans text-[15px] font-semibold text-white shadow-[3px_3px_0_0_#FF48B0] transition-opacity hover:opacity-90"
				>
					Create your own
				</a>
			</div>
		{:else if result}
			<!-- ── Title ─────────────────────────────────────────────────── -->
			<div class="flex flex-col gap-2">
				<p class="font-mono text-[11px] tracking-[0.06em] text-brand-royal">
					SHARED LINK <span class="text-brand-mute">·</span>
					<span class="text-brand-ink">MADE WITH PICTIFY</span>
				</p>
				<h1
					class="font-display text-[34px] font-extrabold leading-[1.06] tracking-[-0.02em] text-brand-ink lg:text-[44px] lg:leading-[50px]"
				>
					{result.title || 'Untitled Creation'}
				</h1>
			</div>

			<!-- ── Proof sheet ───────────────────────────────────────────── -->
			<figure
				class="mx-auto mt-8 w-full max-w-[1200px] overflow-hidden rounded-tile border-[1.5px] border-brand-ink bg-brand-paper shadow-[6px_6px_0_0_#000000]"
			>
				<div
					class="flex items-center justify-between gap-3 border-b-[1.5px] border-brand-ink px-4 py-2.5"
				>
					<span class="flex gap-1" aria-hidden="true">
						<span class="h-2.5 w-2.5 bg-brand-blue" />
						<span class="h-2.5 w-2.5 bg-brand-ink" />
						<span class="h-2.5 w-2.5 bg-brand-pink" />
					</span>
					<span class="font-mono text-[11px] tracking-[0.06em] text-brand-mute">
						{result.width} × {result.height} PX
					</span>
				</div>
				<div class="relative flex justify-center bg-brand-subtle p-3 sm:p-6">
					<img
						src={result.assetUrl}
						alt={result.title || (result.contentType === 'gif' ? 'Generated GIF' : 'Generated image')}
						width={result.width}
						height={result.height}
						class="h-auto max-w-full border border-brand-rule"
					/>
					<a
						href="https://pictify.io"
						target="_blank"
						rel="noopener noreferrer"
						class="absolute bottom-5 right-5 flex items-center gap-1.5 rounded-full border border-brand-ink bg-brand-paper px-3 py-1.5 font-mono text-[10px] tracking-[0.06em] text-brand-ink transition-colors hover:bg-brand-field sm:bottom-9 sm:right-9"
					>
						<span class="h-2 w-2 bg-brand-pink" aria-hidden="true" />
						MADE WITH PICTIFY
					</a>
				</div>
			</figure>

			<!-- ── Ledger + actions ──────────────────────────────────────── -->
			<div
				class="mx-auto mt-6 flex w-full max-w-[1200px] flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"
			>
				<dl class="flex flex-wrap gap-x-6 gap-y-2">
					{#each ledger as [label, value] (label)}
						<div class="flex items-baseline gap-2">
							<dt class="font-mono text-[11px] tracking-[0.06em] text-brand-mute">{label}</dt>
							<dd class="font-mono text-xs tracking-[0.06em] text-brand-ink">{value}</dd>
						</div>
					{/each}
				</dl>

				<div class="flex flex-wrap gap-3">
					<div class="download-dropdown relative">
						<button
							type="button"
							on:click={() => (downloadOpen = !downloadOpen)}
							aria-expanded={downloadOpen}
							class="flex items-center gap-2 rounded-lg bg-brand-ink px-6 py-3.5 font-sans text-[15px] font-semibold text-white shadow-[3px_3px_0_0_#FF48B0] transition-opacity hover:opacity-90"
						>
							Download
							<span class="font-mono text-xs transition-transform {downloadOpen ? 'rotate-180' : ''}" aria-hidden="true">▾</span>
						</button>
						{#if downloadOpen}
							<div
								class="absolute right-0 top-full z-30 mt-2 w-48 overflow-hidden rounded-tile border-[1.5px] border-brand-ink bg-brand-paper"
							>
								{#each ['png', 'jpg', 'webp'] as fmt}
									{@const isOriginal = (result.format || 'png').toLowerCase() === fmt}
									<button
										type="button"
										on:click={() => downloadAsset(fmt)}
										class="flex w-full items-center justify-between px-4 py-3 text-left font-mono text-xs tracking-[0.06em] text-brand-ink transition-colors hover:bg-brand-field {downloading ===
										fmt
											? 'opacity-50'
											: ''}"
									>
										<span>{fmt.toUpperCase()}</span>
										{#if isOriginal}
											<span class="text-[10px] text-brand-mute">ORIGINAL</span>
										{/if}
									</button>
								{/each}
							</div>
						{/if}
					</div>

					<button
						type="button"
						on:click={copyShareUrl}
						class="rounded-lg border-[1.5px] border-brand-ink bg-brand-paper px-6 py-3.5 font-sans text-[15px] font-semibold text-brand-ink transition-colors hover:bg-brand-subtle"
					>
						Copy link
					</button>
				</div>
			</div>

			<!-- ── Embed codes + context ─────────────────────────────────── -->
			<div class="mx-auto mt-12 grid w-full max-w-[1200px] grid-cols-1 gap-8 lg:grid-cols-12">
				<div class="flex flex-col gap-3 lg:col-span-7">
					<p class="font-mono text-xs tracking-[0.06em] text-brand-mute">EMBED IT</p>
					<div class="overflow-hidden rounded-tile bg-brand-press">
						<div class="flex overflow-x-auto border-b border-brand-slate" role="tablist">
							{#each embedTabs as tab (tab.key)}
								<button
									type="button"
									role="tab"
									aria-selected={activeEmbedTab === tab.key}
									on:click={() => (activeEmbedTab = tab.key)}
									class="flex-1 whitespace-nowrap px-4 py-3 font-mono text-[11px] tracking-[0.06em] transition-colors {activeEmbedTab ===
									tab.key
										? 'border-b-2 border-brand-field text-brand-field'
										: 'text-brand-press-text hover:text-white'}"
								>
									{tab.label}
								</button>
							{/each}
						</div>
						<div class="relative p-4 pr-20">
							<pre
								class="whitespace-pre-wrap break-all font-mono text-xs leading-[19px] text-brand-press-text"><code
									>{@html highlightSnippet(embedSnippets[activeEmbedTab] || '')}</code
								></pre>
							<button
								type="button"
								on:click={() => copyEmbedCode(activeEmbedTab)}
								class="absolute right-3 top-3 font-mono text-[11px] tracking-[0.06em] text-brand-field hover:underline"
							>
								COPY
							</button>
						</div>
					</div>
				</div>

				<div class="flex flex-col gap-6 lg:col-span-5">
					<!-- Context card for visitors, styled as the rail signup card. -->
					{#if ctaConfig && !isLoggedIn}
						<div
							class="flex flex-col gap-3.5 border-2 border-brand-ink bg-brand-paper p-6 shadow-[6px_6px_0_0_#0078BF]"
						>
							<div class="flex gap-1" aria-hidden="true">
								<span class="h-2.5 w-2.5 bg-brand-blue" />
								<span class="h-2.5 w-2.5 bg-brand-ink" />
								<span class="h-2.5 w-2.5 bg-brand-pink" />
							</div>
							<p class="font-mono text-xs tracking-[0.06em] text-brand-mute">
								{ctaConfig.sidebar.heading.toUpperCase()}
							</p>
							<p class="font-display text-2xl font-bold leading-[30px] tracking-[-0.02em] text-brand-ink">
								Turn this design into a template.
							</p>
							<p class="font-sans text-[15px] leading-[23px] text-brand-slate">
								{#if result.source === 'tool'}
									Generate images like this one instantly with our free tool.
								{:else if result.source === 'template'}
									Customize this template with your own data and branding.
								{:else if result.source === 'api'}
									One API call. Any template. Infinite images.
								{:else}
									Create, customize, and automate image generation.
								{/if}
							</p>
							<button
								type="button"
								on:click={handleSidebarCta}
								class="flex items-center justify-center bg-brand-ink p-3.5 font-sans text-[15px] font-medium text-white shadow-[3px_3px_0_0_#FF48B0] transition-opacity hover:opacity-90"
							>
								{ctaConfig.sidebar.button}
							</button>
						</div>
					{/if}

					<!-- Analytics (visible to creator and team members) -->
					{#if isLoggedIn && (analytics || analyticsLoading)}
						<div class="flex flex-col rounded-tile border-[1.5px] border-brand-ink bg-brand-paper">
							<p
								class="border-b border-brand-rule px-5 py-3 font-mono text-[11px] tracking-[0.06em] text-brand-mute"
							>
								ANALYTICS{isCreator ? ' · YOUR RENDER' : ''}
							</p>
							<div class="flex flex-col gap-5 p-5">
								{#if analyticsLoading}
									<p class="font-mono text-xs tracking-[0.06em] text-brand-mute">LOADING ANALYTICS…</p>
								{:else if analytics}
									<div class="grid grid-cols-2 gap-2">
										<div class="flex flex-col gap-1 bg-brand-subtle p-3">
											<span class="font-display text-2xl font-bold leading-7 text-brand-ink"
												>{(analytics.totalHits || 0).toLocaleString()}</span
											>
											<span class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">TOTAL HITS</span>
										</div>
										<div class="flex flex-col gap-1 bg-brand-subtle p-3">
											<span class="font-display text-2xl font-bold leading-7 text-brand-ink"
												>{formatBytes(analytics.totalBytes || 0)}</span
											>
											<span class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">BANDWIDTH</span>
										</div>
									</div>

									{#if analytics.statusCodes}
										{@const sc = analytics.statusCodes}
										{@const scTotal = (sc._200 || 0) + (sc._304 || 0) + (sc._other || 0)}
										{#if scTotal > 0}
											<div class="grid grid-cols-3 gap-2">
												{#each [['200 OK', sc._200], ['304 CACHE', sc._304], ['OTHER', sc._other]] as [label, count] (label)}
													<div class="flex flex-col gap-0.5 border border-brand-rule p-2">
														<span class="font-mono text-xs text-brand-ink">{count || 0}</span>
														<span class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">{label}</span>
													</div>
												{/each}
											</div>
										{/if}
									{/if}

									{#if analytics.dailyStats?.length > 1}
										{@const maxHits = Math.max(...analytics.dailyStats.map((d) => d.hits), 1)}
										<div class="flex flex-col gap-1.5">
											<p class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">HITS · LAST 14 DAYS</p>
											<div class="flex h-14 items-end gap-0.5">
												{#each analytics.dailyStats.slice(-14) as day}
													<div
														class="flex-1 cursor-default bg-brand-blue transition-colors hover:bg-brand-ink"
														style="height: {Math.max((day.hits / maxHits) * 100, 4)}%"
														title="{day.date}: {day.hits} hits"
													/>
												{/each}
											</div>
										</div>
									{/if}

									{#if analytics.topReferrers?.length}
										<div class="flex flex-col gap-1.5 border-t border-brand-rule pt-4">
											<p class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">REFERRERS</p>
											{#each analytics.topReferrers.slice(0, 5) as ref}
												<div class="flex items-center justify-between gap-3 font-sans text-[13px]">
													<span class="max-w-[200px] truncate text-brand-slate">{ref.referrer || 'Direct'}</span>
													<span class="font-mono text-xs text-brand-ink">{ref.hits}</span>
												</div>
											{/each}
										</div>
									{/if}

									{#if analytics.topCountries?.length}
										<div class="flex flex-col gap-2 border-t border-brand-rule pt-4">
											<p class="font-mono text-[10px] tracking-[0.06em] text-brand-mute">GEOGRAPHY</p>
											{#each analytics.topCountries.slice(0, 5) as geo}
												{@const pct = Math.round((geo.hits / (analytics.totalHits || 1)) * 100)}
												<div class="flex flex-col gap-1">
													<div class="flex items-center justify-between font-sans text-[13px]">
														<span class="text-brand-slate">{geo.country}</span>
														<span class="font-mono text-xs text-brand-ink"
															>{geo.hits} <span class="text-brand-mute">({pct}%)</span></span
														>
													</div>
													<div class="h-1 overflow-hidden bg-brand-subtle">
														<div class="h-full bg-brand-blue" style="width: {pct}%" />
													</div>
												</div>
											{/each}
										</div>
									{/if}

									{#if analytics.lastProcessedAt}
										<div
											class="flex items-center justify-between border-t border-brand-rule pt-4 font-mono text-[11px] tracking-[0.06em]"
										>
											<span class="text-brand-mute">LAST UPDATED</span>
											<span class="text-brand-ink">{formatDate(analytics.lastProcessedAt).toUpperCase()}</span>
										</div>
									{/if}
								{:else}
									<p class="font-sans text-sm text-brand-slate">
										Analytics will appear here once this asset gets traffic.
									</p>
								{/if}
							</div>
						</div>
					{/if}
				</div>
			</div>
		{/if}
	</main>

	<!-- ── Closing band (visitors only) ──────────────────────────────── -->
	{#if result && !isLoggedIn}
		<section class="w-full bg-brand-press-deep px-5 py-14 lg:px-10 lg:py-20">
			<div
				class="mx-auto flex w-full max-w-page flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"
			>
				<div class="flex flex-col gap-3.5 lg:max-w-[680px]">
					<p class="font-mono text-xs tracking-[0.06em] text-brand-field">MADE WITH PICTIFY</p>
					<h2
						class="font-display text-[32px] font-bold leading-[1.08] tracking-[-0.02em] text-white lg:text-[44px] lg:leading-[50px]"
					>
						{ctaConfig?.banner?.headline || 'DESIGN. AUTOMATE. SCALE.'}
					</h2>
					<p class="font-sans text-base leading-[25px] text-brand-press-text">
						{ctaConfig?.banner?.body || 'Create images, GIFs, and PDFs. Automate with the API.'}
					</p>
				</div>

				<div class="flex flex-wrap gap-3">
					<a
						href="/signup"
						class="rounded-lg bg-brand-field px-7 py-4 font-sans text-base font-semibold text-brand-ink shadow-[3px_3px_0_0_#FF48B0] transition-opacity hover:opacity-90"
					>
						{result.source === 'api' ? 'Get API Key' : 'Start Free'}
					</a>
					<a
						href="/tools"
						class="rounded-lg border-[1.5px] border-white px-7 py-4 font-sans text-base font-semibold text-white transition-colors hover:bg-white/10"
					>
						Try the Free Tools
					</a>
				</div>
			</div>
		</section>
	{/if}

	<Footer />
</div>
